name              "liferay"
maintainer        "Thirdwave, LLC"
maintainer_email  "adam.krone@thirdwavellc.com"
license           "Apache 2.0"
description       "Installs and configures Liferay"
version           "0.13.1"

depends "apt"
depends "yum"
depends "imagemagick"
depends "java"
