name              "liferay"
maintainer        "Thirdwave, LLC"
maintainer_email  "adam.krone@thirdwavellc.com"
license           "Apache 2.0"
description       "Installs and configures Liferay"
version           "0.11.0"

depends "apt"
depends "unzip"
depends "imagemagick"
depends "java"
depends "database"
depends "postgresql"
depends "mysql"
depends "mysql-connector"
